# .gitlab-ci.yml
image: docker:latest
services:
  - docker:dind

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/allan.i/smartnew:$CI_BUILD_REF_NAME

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build --file="docker/php7-fpm/Dockerfile" --tag="$CONTAINER_TEST_IMAGE" .
    - docker run --name gitlab-mysql -e MYSQL_DATABASE=database_test -e MYSQL_USER=database_test -e MYSQL_PASSWORD=database_test -e MYSQL_ROOT_PASSWORD=root -d mysql:5.7
    - docker run --link gitlab-mysql:test-mysql $CONTAINER_TEST_IMAGE php bin/console doctrine:schema:update --force --env=test
    - docker run --link gitlab-mysql:test-mysql $CONTAINER_TEST_IMAGE tests
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker push $CONTAINER_TEST_IMAGE

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  only:
    - master
  script:
    - echo "Deployment not configured"
