services:
#    market.example:
#        class: MarketBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    exchange.manager:
        class: MarketBundle\Service\ExchangeManager
        public: true
        arguments: ["%exchanges%"]

    markets.update.ohlc:
        class: MarketBundle\Service\MarketsOHLCUpdateService
        public: true
        arguments: [ "@exchange.manager", %markets.symbols%]
