<?php

namespace MarketBundle\Repository;

/**
 * CandlestickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandlestickRepository extends \Doctrine\ORM\EntityRepository
{
}
