<?php

namespace MarketBundle\Repository;
use MarketBundle\Entity\Market;

/**
 * CandlestickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandlestickRepository extends \Doctrine\ORM\EntityRepository{

    /**
     * This method returns the last candle for the specified market
     * @param Market $market
     * @return int
     */
    public function getLastCandleFor(Market $market){

        $q = $this->createQueryBuilder('c');
        $q
            ->select('c')
            ->where('c.market = :market')
            ->setParameter('market', $market)
            ->orderBy('c.timestamp', 'DESC')
            ;

        return $q->getQuery()->getFirstResult();
    }
}
