version: '2'

services:
    php:
        build:
            context: php7-fpm
        volumes:
            - ../symfony:/var/www/symfony
    nginx:
        build: nginx
        ports:
            - ${HOST_HTTP_PORT}:80
        volumes_from:
            - php
    memcached:
        image: memcached:alpine
        links:
          - php
    db:
      image: postgres
      restart: always
      volumes:
          - "../data/postgresql_data:/var/lib/postgresql/data"
      links:
        - php
      environment:
          POSTGRES_DB: ${DB_DATABASE}
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
