
version: '2'

services:
    php:
#        image: registry.gitlab.com/allan.i/smartnew:php-master
        build:
          context: ../
          dockerfile: docker/php7-fpm/Dockerfile
        volumes:
            - ../symfony:/var/www/symfony
    nginx:
        image: registry.gitlab.com/allan.i/smartnew:nginx-master
#        ports:
#            - ${HOST_HTTP_PORT}:80
        volumes_from:
            - php
    memcached:
        image: memcached:alpine
        links:
          - php
#    db:
#        image: mysql:5.7
#        volumes:
#            - ../data/db:/var/lib/mysql
#        environment:
#            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#            MYSQL_DATABASE: ${DB_DATABASE}
#            MYSQL_USER: ${DB_USER}
#            MYSQL_PASSWORD: ${DB_PASSWORD}
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        environment:
#            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#        ports:
#            - "${HOST_PMA_HTTP_PORT}:80"
#        links:
#            - db
